=== visma/isma-tools/isma-tools-cv/src/main/resources/org/isma/tools/cv/cv.xsd
<?xml version="1.0" encoding="iso-8859-1" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <!-- ==================== ROOT ELEMENT ==================== -->
    <xs:element name="cv">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="cv-type">
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>

    <!-- ==================== 2nd LEVEL ELEMENTS ==================== -->
    <xs:element name="candidat">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="contact" maxOccurs="1"/>
                <xs:element ref="adresse" maxOccurs="1"/>
                <xs:element ref="profil" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute name="prenom" type="xs:string" use="required"/>
            <xs:attribute name="nom" type="xs:string" use="required"/>
            <xs:attribute name="age" type="xs:integer" use="required"/>
            <xs:attribute name="statutMarital" type="xs:string" use="required"/>
            <xs:attribute name="nationalite" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="formations">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="formation" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="experiences">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="pageExperience" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="langues">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="langue" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <!--<xs:element name="competences">-->
    <!--<xs:complexType>-->
    <!--<xs:sequence>-->
    <!--<xs:element ref="domaine" maxOccurs="unbounded"/>-->
    <!--</xs:sequence>-->
    <!--</xs:complexType>-->
    <!--</xs:element>-->
    <!-- ==================== 3nd LEVEL ELEMENTS ==================== -->
    <xs:element name="pageExperience">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="experience" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="contact">
        <xs:complexType>
            <xs:attribute name="mail" type="xs:string" use="required"/>
            <xs:attribute name="tel" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="adresse">
        <xs:complexType>
            <xs:attribute name="rue" type="xs:string" use="required"/>
            <xs:attribute name="cp" type="xs:integer" use="required"/>
            <xs:attribute name="ville" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="profil">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="competences"/>
            </xs:sequence>
            <xs:attribute name="titre" type="xs:string" use="required"/>
            <xs:attribute name="description" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="formation">
        <xs:complexType>
            <xs:attribute name="nom" type="xs:string" use="required"/>
            <xs:attribute name="annee" type="xs:integer" use="required"/>
            <xs:attribute name="specialisation" type="xs:string" use="optional"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="langue">
        <xs:complexType>
            <xs:attribute name="nom" type="xs:string" use="required"/>
            <xs:attribute name="niveau" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    <!-- ==================== 4th LEVEL ELEMENTS ==================== -->
    <xs:element name="experience">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="client"/>
                <xs:element ref="mission"/>
                <xs:element ref="projets"/>
                <xs:element ref="intervention" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="environnement" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="competences">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="competence" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <!-- ==================== 5th LEVEL ELEMENTS ==================== -->
    <xs:element name="client">
        <xs:complexType>
            <xs:attribute name="nom" type="xs:string" use="required"/>
            <xs:attribute name="fonction" type="xs:string" use="required"/>
            <xs:attribute name="equipe" type="xs:string" use="optional"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="mission">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="texte" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute name="poste" type="xs:string" use="required"/>
            <xs:attribute name="duree" type="xs:string" use="required"/>
            <xs:attribute name="dateDebut" type="xs:string" use="required"/>
            <xs:attribute name="dateFin" type="xs:string" use="required"/>
            <xs:attribute name="type" type="typeMission" use="required"/>
            <xs:attribute name="effectifs" type="xs:string" use="required"/>

        </xs:complexType>
    </xs:element>
    <xs:element name="projets">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="projet" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="intervention">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="texte"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="environnement">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded" minOccurs="0">
                <xs:element ref="texte"/>
                <xs:element ref="liste"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>    <xs:element name="competence">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="detail" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="intitule" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
    <!-- ==================== 6th LEVEL ELEMENTS ==================== -->
    <xs:element name="projet">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="texte"/>
            </xs:sequence>
            <xs:attribute name="nom" type="xs:string" use="optional"/>
        </xs:complexType>
    </xs:element>
    <!-- ==================== COMMON ELEMENT ==================== -->
    <xs:element name="texte"/>
    <xs:element name="element"/>
    <xs:element name="liste">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded">
                <xs:element ref="element"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="cvweight">
        <xs:restriction base="xs:string">
            <xs:enumeration value="light"/>
            <xs:enumeration value="heavy"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="typeMission">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Stage"/>
            <xs:enumeration value="Régie"/>
            <xs:enumeration value="Forfait"/>
            <xs:enumeration value="Interne" />
            <xs:enumeration value="Contrat de qualification" />
            <xs:enumeration value="Création d'entreprise" />
        </xs:restriction>
    </xs:simpleType>


    <xs:complexType name="cv-type">
        <xs:sequence>
            <xs:element ref="candidat"/>
            <xs:element ref="formations"/>
            <xs:element ref="experiences"/>
            <xs:element ref="langues"/>
            <!--<xs:element ref="competences"/>-->
        </xs:sequence>
        <xs:attribute name="cvweight" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="light"/>
                    <xs:enumeration value="heavy"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
</xs:schema>

=== visma/isma-tools/isma-tools-cv/src/main/resources/org/isma/tools/cv/cv_MAMECHE.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<cv xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="cv.xsd" cvweight="heavy">
    <candidat prenom="Ismaël" nom="MAMECHE" age="32" statutMarital="Célibataire" nationalite="française">
        <contact mail="ismael.mameche@gmail.com" tel="06 76 40 15 17"/>
        <adresse rue="14 avenue joffre" cp="94160" ville="Saint mandé"/>
        <profil titre="Développeur Java senior"
                description="8 ans d'expérience, agiliste, spécialiste du monde java">
            <competences>
                <competence intitule="Maîtrise du langage Java, du framework JEE, de son API et de ses outils">
                    <detail>Eclipse</detail>
                    <detail>Intellij</detail>
                    <detail>Tomcat</detail>
                    <detail>Websphere</detail>
                    <detail>Yourkit</detail>
                </competence>
                <competence intitule="Expérimenté sur de nombreux frameworks, librairies et design patterns">
                    <detail>Swing</detail>
                    <detail>JEE</detail>
                    <detail>Spring</detail>
                    <detail>Struts</detail>
                    <detail>Hibernate</detail>
                    <detail>REST/JSON</detail>
                    <detail>Apache Commons</detail>
                    <detail>Pico</detail>
                    <detail>Mockito</detail>
                    <detail>Log4j</detail>
                    <detail>JUnit</detail>
                </competence>
                <competence intitule="Expérimenté dans l'utilisation d'une forge logicielle">
                    <detail>Intégration continue (Bamboo, Hudson/Jenkins)</detail>
                    <detail>Maven</detail>
                    <detail>Test coverage (Cobertura)</detail>
                </competence>
                <competence intitule="Bonne connaissances en développement web">
                    <detail>XHTML</detail>
                    <detail>JavaScript</detail>
                    <detail>CSS</detail>
                    <detail>XML</detail>
                    <detail>XSD</detail>
                    <detail>JQuery</detail>
                    <!--<detail>Backbone.</detail>-->
                    <!--<detail>Websockets</detail>-->
                </competence>
                <competence intitule="Expérimenté en bases de données relationnelles">
                    <detail>MySQL</detail>
                    <detail>Oracle</detail>
                    <detail>SQL Server</detail>
                    <detail>Sybase</detail>
                    <detail>Transact-SQL</detail>
                </competence>
                <competence intitule="Expérimenté dans les bonnes pratiques issues des méthodologies agiles">
                    <detail>Test Driven Developpement</detail>
                    <detail>
                        <![CDATA[
                        Scrum, eXtreme Programming (Itérations courtes, intégration continue, travail en binôme, plannification et estimation de charge des tâches)
                        ]]>
                    </detail>
                </competence>
            </competences>
        </profil>
    </candidat>
    <formations>
        <formation nom="Baccalauréat S" annee="1998"/>
        <formation nom="Diplôme d'ingénieur EPITA" annee="2004"
                   specialisation="Spécialisation systèmes d'information et génie logiciel"/>
    </formations>
    <experiences>
        <pageExperience>
            <!-- PMU -->
            <experience>
                <client nom="PMU" fonction="Jeux en ligne" equipe="D2I (WebServices)"/>
                <mission poste="Ingénieur étude et développement" duree="3 mois" dateDebut="octobre 2012"
                         dateFin="decembre 2012" type="Forfait" effectifs="20">
                    <texte>
                        <![CDATA[
                    L'équipe PMU Connect services est en charge de la refonte du site internet du PMU.
                    Le site internet couvre la gestion du compte utilisateur, ainsi que la prise de pari hippique, sportive et le poker.
                    Le rôle de l'équipe services consiste a créer l'ensemble des webservices dont a besoin l'équipe Front.
                    ]]>
                    </texte>
                </mission>
                <projets>
                    <projet nom="PMU Connect">
                        <texte>
                            <![CDATA[
                        <p>La nouvelle monture du site internet PMU Connect couvre :</p>
                        <ul class="projectlist">
                            <li>la gestion de compte utilisateur (autolimitations...)</li>
                            <li>la prise de pari hippique et sportive</li>
                            <li>la restitution des informations hippiques des fournisseurs de données (equidia, geny...)</li>
                            <li>le poker en ligne</li>
                        </ul>
                        ]]>
                        </texte>
                    </projet>
                </projets>
                <intervention>
                    <texte>
                        <![CDATA[
                        Mes interventions sur site ou en télétravail couvrent :
                        <ul class="interventionList">
                            <li>Chiffrages (sprint planning)</li>
                            <li>Analyse</li>
                            <li>Validation de l'api JSON des services auprès du Front</li>
                            <li>Tests unitaires (TDD, BDD...)</li>
                            <li>Conception/Développement des services</li>
                            <li>Rédaction des tests d'acceptance</li>
                            <li>Démonstration (sprint demo)</li>
                        </ul>
                        ]]>
                    </texte>
                </intervention>
                <environnement>
                    <liste>
                        <element>Méthodologie Scrum (daily scrum, sprint planning, sprint demo, retrospective...)</element>
                        <element>Intégration continue (Jenkins, Sonar, Fortify)</element>
                        <element>Test Driven Developpement</element>
                        <element>Tomcat</element>
                        <element>Java 7</element>
                        <element>Maven 3</element>
                        <element>Rest/JSON</element>
                        <element>Spring 3 (ioc, security, aop)</element>
                        <element>Hibernate 3</element>
                        <element>JMS</element>
                        <element>Mockito</element>
                        <element>JBehave</element>
                        <element>JMeter</element>
                        <element>Intellij</element>
                        <element>memcached</element>
                        <element>Mysql</element>
                        <element>Jira/Confluence</element>
                        <!--<element>SVN</element>-->
                        <element>MacOs X</element>
                        <element>Skype</element>
                    </liste>
                </environnement>
            </experience>
            <!-- ALLIANZ -->
            <experience>
                <client nom="Allianz Global Investors" fonction="Asset Manager" equipe="Front Office"/>
                <mission poste="Ingénieur étude et développement" duree="3.5 ans" dateDebut="Juin 2008"
                         dateFin="Février 2012" type="Régie" effectifs="10~15">
                    <texte>
                        <![CDATA[
                    L'équipe IT Front / IT Risk d'AGI assure l'évolution et la maintenance des applications front office.
                    Ces applications sont construites à partir d'un datawarehouse alimenté par les bases de données des progiciels DECALOG et TRADIX.
                    ]]>
                    </texte>
                </mission>
                <projets>
                    <projet nom="GPTaux">
                        <texte>
                            <![CDATA[
                        <p>L'application GPTaux couvre :</p>
                        <ul class="projectlist">
                            <li>la gestion de portefeuilles de taux à partir des instruments et positions de DECALOG</li>
                            <li>la gestion de portefeuilles monétaires à partir des instruments et positions de TRADIX</li>
                            <li>le référentiel des instruments dérivés dont le pricing est effectué par REECH</li>
                        </ul>
                        ]]>
                        </texte>
                    </projet>
                    <projet nom="Oscar">
                        <texte>
                            <![CDATA[
                            Application d'administration des données du Datawarehouse
                            ]]>
                        </texte>
                    </projet>
                </projets>
                <intervention>
                    <texte>
                        <![CDATA[
                        <p>Mes interventions en maîtrise d'oeuvre couvrent :</p>
                        <ul class="interventionList">
                            <li>conception/développement JAVA (2 ou 3 tiers), architecture client de type MVC</li>
                            <li>l'écriture du mapping objet/relationnel en XML</li>
                            <li>l'écriture des requêtes et procédures stoquées SQL</li>
                            <li>la définition et l'écriture des données fournies en entrée aux tests automatisés</li>
                            <li>la définition et l'écriture des étalons de tests (résultats attendus)</li>
                            <li>l'estimation de la charge de travail des différentes tâches</li>
                        </ul>
